name: Build partner-chains-node and partner-chains-cli and push to binary-host

on:
  workflow_dispatch:
    inputs:
      push_to_binary_host:
        description: "Push to binary-host"
        type: boolean
        required: true

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Earthly
        uses: ./.github/earthly-setup
        with:
          ssh_key: ${{ secrets.SUBSTRATE_REPO_SSH_KEY }}
          config_tar: ${{ secrets.EARTHLY_TAR }}

      - name: Run Earthly build
        run: |
          export EARTHLY_OUTPUT=true
          earthly +build

      - name: Extract partner-chains-node and partner-chains-cli
        run: |
          mkdir -p artifact
          cp ./partner-chains-node ./partner-chains-cli-artifact artifact/

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: substrate-binaries
          path: artifact/

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: substrate-binaries
          path: artifact/

  kubectl-cp-to-binary-host:
    runs-on: [self-hosted, eks]
    needs: build-and-upload
    if: ${{ github.event.inputs.push_to_binary_host == 'true' }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Install kubectl and awscli
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          sudo apt update && sudo apt install -y awscli

      - name: Configure kubectl
        run: |
          echo "${{ secrets.kubeconfig_base64 }}" | base64 --decode > ${{ runner.temp }}/kubeconfig.yaml
          kubectl config set-cluster my-cluster --server=${{ secrets.K8S_SERVER }} --insecure-skip-tls-verify=true
          kubectl config set-credentials github-actions --token=${{ secrets.K8S_SA_TOKEN }}
          kubectl config set-context my-context --cluster=my-cluster --user=github-actions --namespace=default
          kubectl config use-context my-context

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: substrate-binaries
          path: artifact/

      - name: Copy binaries to binary-host
        run: |
          kubectl cp ./artifact/partner-chains-node binary-host:/tools/partner-chains-node -c binary-host -n sc
          kubectl cp ./artifact/partner-chains-cli-artifact binary-host:/tools/partner-chains-cli -c binary-host -n sc
