name: Build sidechain-main-cli and Push to EKS binary-host (optional)

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to build from"
        required: true
        default: ""
      push_to_binary_host:
        description: "Push to binary-host"
        required: true
        type: boolean

jobs:
  build-and-upload:
    runs-on: [self-hosted, nixos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: input-output-hk/partner-chains-smart-contracts
          token: ${{ secrets.ACTIONS_PAT }}
          ref: ${{ github.event.inputs.commit_sha }}
          path: partner-chains-smart-contracts

      - name: Build
        run: nix build ./partner-chains-smart-contracts#sidechain-release-bundle

      - name: Prepare Artifact
        run: |
          mkdir -p partner-chains-smart-contracts-artifact
          cp result/* partner-chains-smart-contracts-artifact

      - name: Upload Directory as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: partner-chains-smart-contracts-artifact
          path: partner-chains-smart-contracts-artifact/

      - name: Post-build Cleanup
        run: rm -rf partner-chains-smart-contracts-artifact

  unzip-and-rename-artifact:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Download sidechain-main-cli Artifact
        uses: actions/download-artifact@v4
        with:
          name: partner-chains-smart-contracts-artifact
          path: artifact/

      - name: Unzip Artifact
        run: |
          mkdir -p artifact/unzipped
          unzip artifact/release.zip -d artifact/unzipped

      - name: Rename Binary
        run: |
          mv artifact/unzipped/sidechain-cli artifact/unzipped/sidechain-main-cli

      - name: Upload Unzipped Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unzipped
          path: artifact/unzipped

  kubectl-cp-to-binary-host:
    runs-on: [self-hosted, eks]
    needs: unzip-and-rename-artifact
    if: ${{ github.event.inputs.push_to_binary_host }} == 'true'
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Install kubectl and awscli
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          sudo apt update && sudo apt install -y awscli

      - name: Configure kubectl
        run: |
          echo "${{ secrets.kubeconfig_base64 }}" | base64 --decode > ${{ runner.temp }}/kubeconfig.yaml
          kubectl config set-cluster my-cluster --server=${{ secrets.K8S_SERVER }} --insecure-skip-tls-verify=true
          kubectl config set-credentials github-actions --token=${{ secrets.K8S_SA_TOKEN }}
          kubectl config set-context my-context --cluster=my-cluster --user=github-actions --namespace=default
          kubectl config use-context my-context

      - name: Download Unzipped Artifact
        uses: actions/download-artifact@v4
        with:
          name: unzipped
          path: artifact/unzipped

      - name: Create SHA directory on binary-host
        run: |
          kubectl exec binary-host -c binary-host -n sc -- mkdir -p /tools/sidechain-main-cli/${{ github.event.inputs.commit_sha }}

      - name: Copy to binary-host
        run: |
          kubectl cp artifact/unzipped/sidechain-main-cli binary-host:/tools/sidechain-main-cli/${{ github.event.inputs.commit_sha }} -c binary-host -n sc
          kubectl cp artifact/unzipped/node_modules binary-host:/tools/sidechain-main-cli/${{ github.event.inputs.commit_sha }} -c binary-host -n sc

      - name: Make binary executable
        run: |
          kubectl exec binary-host -c binary-host -n sc -- chmod +x /tools/sidechain-main-cli/${{ github.event.inputs.commit_sha }}/sidechain-main-cli
